annomerge: change int cast to float
We sometimes encountered:

  ValueError: invalid literal for int() with base 10: '100.000'

so since 100.000 can't be cast to an int, might as well float it.