Declare minimum required python version as 3.12
We unknowingly relied on some improved f-string handling in 3.12.
With 3.11, we see the error:

```
lib/python3.11/site-packages/hybran/bio.py", line 249
    """
       ^
SyntaxError: f-string expression part cannot include a backslash
```